apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: cloud-project
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "projeto"
        - name: POSTGRES_USER
          value: "projeto_user"
        - name: POSTGRES_PASSWORD
          value: "projeto_password"
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
